INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
	('drug_phone', 'Dokia Phone', 0, 0, 1),
	('pseudoephedrine', 'Pseudoephedrine', 0, 0, 1),
	('red_phosphorus', 'Red Phosphorus', 0, 0, 1),
	('hydrochloric_acid', 'Hydrochloric Acid', 0, 0, 1),
	('lithium', 'Lithium', 0, 0, 1),
	('anhydrous_ammonia', 'Anhydrous Ammonia', 0, 0, 1),
	('meth_oil', 'Methamphetamine oil', 0, 0, 1),
	('methamphetamine_base', 'Methamphetamine base', 0, 0, 1),
	('methamphetamine_hydrochloride', 'Methamphetamine hydrochloride', 0, 0, 1),
	('methamphetamine_crystal', 'Methamphetamine Crystal', 0, 0, 1),
	('microwave', 'Microwave', 0, 0, 1),
	('coca_leaves', 'Coca leaves', 0, 0, 1),
	('coke_filter', 'Coke Filter', 0, 0, 1),
	('coca_leaf_powder', 'Coca leaf powder', 0, 0, 1),
	('water_lab_bottle', 'Big water bottle', 0, 0, 1),
	('coca_gaso_infused', 'Cocaine-infused gasoline', 0, 0, 1),
	('coca_infused_liquid', 'Cocaine liquid', 0, 0, 1),
	('coca_powder', 'Cocaine powder', 0, 0, 1),
	('coke_brick', 'Cocaine brick', 0, 0, 1),
	('coke_baggy', 'Cocaine baggy', 0, 0, 1),
	('meth_baggy', 'Methamphetamine baggy', 0, 0, 1),
	('unpackaged_meth', 'Unpackaged methamphetamine', 0, 0, 1),
	('empty_pot', 'Empty pot', 0, 0, 1),
	('dirt_bag', 'Dirt bag', 0, 0, 1),
	('standing_fan', 'Standing fan', 0, 0, 1),
	('weed_spray_bottle', 'Spray bottle', 0, 0, 1),
	('weed_fertilizer', 'Weed fertilizer', 0, 0, 1),
	('weed_leaf_whitewidow', 'Weed leaf whitewidow', 0, 0, 1),
	('weed_leaf_skunk', 'Weed leaf skunk', 0, 0, 1),
	('weed_leaf_purplehaze', 'Weed leaf purplehaze', 0, 0, 1),
	('weed_leaf_og_kush', 'Weed leaf og kush', 0, 0, 1),
	('weed_leaf_amnesia', 'Weed leaf amnesia', 0, 0, 1),
	('weed_dried_leaf_whitewidow', 'Dried leaf whitewidow', 0, 0, 1),
	('weed_dried_leaf_skunk', 'Dried leaf skunk', 0, 0, 1),
	('weed_dried_leaf_purplehaze', 'Dried leaf purplehaze', 0, 0, 1),
	('weed_dried_leaf_og_kush', 'Dried leaf og kush', 0, 0, 1),
	('weed_dried_leaf_amnesia', 'Dried leaf amnesia', 0, 0, 1),
	('small_fan', 'Small fan', 0, 0, 1),
	('weed_light', 'Weed light', 0, 0, 1),
	('weed_baggy', 'Weed baggy', 0, 0, 1),
	('lab_coat', 'Lab coat', 0, 0, 1),
	('hammer', 'Hammer', 0, 0, 1),
	('empty_m_bag', 'Empty bag', 0, 0, 1),
	('weed_whitewidow_seed', 'Weed whitewidow seed', 0, 0, 1),
	('weed_skunk_seed', 'Weed skunk seed', 0, 0, 1),
	('weed_purplehaze_seed', 'Weed purplehaze seed', 0, 0, 1),
	('weed_ogkush_seed', 'Weed og kush seed', 0, 0, 1),
	('weed_amnesia_seed', 'Weed amnesia seed', 0, 0, 1);

